.PHONY: build dev prod playground backoffice

build:
	npm run build

dev:
	npm run dev

prod:
	npm run prod

playground:
	open http://127.0.0.1:3000/playground > /dev/null 2>&1 &

backoffice:
	open http://127.0.0.1:3000/backoffice > /dev/null 2>&1 &
