.PHONY: build start playground backoffice

build:
	npm run build

serve:
	npm run serve

playground:
	open http://127.0.0.1:3000/playground > /dev/null 2>&1 &

backoffice:
	open http://127.0.0.1:3000/backoffice > /dev/null 2>&1 &
